# Generated by Django 4.2.11 on 2024-05-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee_edited',
            name='student',
        ),
        migrations.AddField(
            model_name='fee_edited',
            name='student_edited',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fee_edited', to='student.student_edited'),
            preserve_default=False,
        ),
    ]
