# Generated by Django 4.2.11 on 2024-05-01 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Teacher Profile Update'), (2, 'New Teacher Request'), (3, 'New Student Enrollment'), (4, 'Fee Payment Reminder'), (5, 'Class Session'), (6, 'Exam Schedule'), (7, 'Attendance'), (8, 'Assignment Submission'), (9, 'Grading'), (10, 'System Maintenance'), (11, 'Student Profile Update'), (12, 'New Administrator Request')]),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 11, 39, 6, 70209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question/'),
        ),
    ]
