# Generated by Django 4.2.11 on 2024-04-10 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 9, 43, 11, 510638, tzinfo=datetime.timezone.utc)),
        ),
    ]
