# Generated by Django 4.2.11 on 2024-05-01 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_librarian',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 11, 51, 16, 721608, tzinfo=datetime.timezone.utc)),
        ),
    ]
