# Generated by Django 4.2.11 on 2024-04-10 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_classsession_active_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='department',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='administration.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 10, 56, 47, 681677, tzinfo=datetime.timezone.utc)),
        ),
    ]
