# Generated by Django 5.0.3 on 2024-04-06 11:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_customuser_otp_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='administration.department'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 11, 25, 29, 607123, tzinfo=datetime.timezone.utc)),
        ),
    ]
