# Generated by Django 4.2.11 on 2024-04-10 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 10, 58, 10, 363522, tzinfo=datetime.timezone.utc)),
        ),
    ]
