# Generated by Django 4.2.11 on 2024-05-05 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 7, 42, 47, 222563, tzinfo=datetime.timezone.utc)),
        ),
    ]
