# Generated by Django 4.2.11 on 2024-05-08 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Teacher Profile Update'), (2, 'New Teacher Request'), (3, 'New Student Enrollment'), (4, 'New Administrator Request'), (5, 'Class Session'), (6, 'Exam Schedule'), (7, 'Attendance'), (8, 'Assignment Submission'), (9, 'Grading'), (10, 'System Maintenance'), (11, 'Student Profile Update'), (12, 'Fee Payment Reminder')]),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 6, 56, 12, 353687, tzinfo=datetime.timezone.utc)),
        ),
    ]
