# Generated by Django 4.2.11 on 2024-05-08 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_notification_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Teacher Profile Update'), (2, 'New Teacher Request'), (3, 'New Student Enrollment'), (4, 'New Administrator Request'), (5, 'Class Session'), (6, 'Exam Schedule'), (7, 'Attendance'), (8, 'Assignment Submission'), (9, 'Grading'), (10, 'System Maintenance'), (11, 'Student Profile Update'), (12, 'Fee Payment Reminder')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 7, 0, 8, 986010, tzinfo=datetime.timezone.utc)),
        ),
    ]
