# Generated by Django 5.0.3 on 2024-04-07 07:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_otp_expires_at_alter_student_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administration',
            new_name='Administrator',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_administrator',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='notification',
            name='administrator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrator_notification', to='administration.administrator'),
        ),
        migrations.AddField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notification', to='administration.teacher'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_notification', to='administration.student'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 7, 44, 1, 148117, tzinfo=datetime.timezone.utc)),
        ),
    ]
