# Generated by Django 4.2.11 on 2024-04-11 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_otp_expires_at_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_oss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_image_path', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option1_image_path', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option2_image_path', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option3_image_path', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('option4_image_path', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=100)),
                ('explanation_image_path', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='table_name',
            new_name='attendence_table_name',
        ),
        migrations.AddField(
            model_name='classsession',
            name='response_table_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='classsession',
            name='result_table_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='classsession',
            name='test_table_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjects_question_table_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 7, 48, 17, 36940, tzinfo=datetime.timezone.utc)),
        ),
    ]
