# Generated by Django 4.2.11 on 2024-04-11 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_question_oss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='administration_2024_cse_Semester_1_OS_attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('is_present', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administration_2024_cse_Semester_1_OS_attendence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='administration_2024_cse_Semester_1_OS_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('is_present', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administration_2024_cse_Semester_1_OS_response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='administration_2024_cse_Semester_1_OS_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('is_present', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administration_2024_cse_Semester_1_OS_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='administration_2024_cse_Semester_1_OS_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('is_present', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administration_2024_cse_Semester_1_OS_test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='question_oss',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 9, 3, 53, 441343, tzinfo=datetime.timezone.utc)),
        ),
    ]
