# Generated by Django 5.0.3 on 2024-04-07 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_rename_administration_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 7, 47, 13, 60023, tzinfo=datetime.timezone.utc)),
        ),
    ]
