# Generated by Django 5.0.3 on 2024-04-07 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_remove_customuser_role_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='department',
        ),
        migrations.AddField(
            model_name='administrator',
            name='departments',
            field=models.ManyToManyField(default=None, related_name='administrators', to='administration.department'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 8, 28, 47, 750627, tzinfo=datetime.timezone.utc)),
        ),
    ]
