# Generated by Django 4.2.11 on 2024-04-11 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_administration_2024_cse_semester_1_os_attendence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administration_2024_cse_Semester_1_OS_attendence',
        ),
        migrations.DeleteModel(
            name='administration_2024_cse_Semester_1_OS_response',
        ),
        migrations.DeleteModel(
            name='administration_2024_cse_Semester_1_OS_result',
        ),
        migrations.DeleteModel(
            name='administration_2024_cse_Semester_1_OS_test',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 9, 6, 39, 753918, tzinfo=datetime.timezone.utc)),
        ),
    ]
