# Generated by Django 4.2.11 on 2024-04-09 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_remove_administrator_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 11, 6, 35, 999689, tzinfo=datetime.timezone.utc)),
        ),
    ]
