# Generated by Django 4.2.11 on 2024-04-11 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_delete_administration_2024_cse_semester_1_os_attendence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='for_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 29, 51, 533078, tzinfo=datetime.timezone.utc)),
        ),
    ]
