# Generated by Django 4.2.11 on 2024-04-09 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_classsession_semester_classsession_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 11, 12, 34, 819267, tzinfo=datetime.timezone.utc)),
        ),
    ]
