# Generated by Django 4.2.11 on 2024-04-12 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_notification_notification_type_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='total_active_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 8, 1, 22, 601774, tzinfo=datetime.timezone.utc)),
        ),
    ]
