# Generated by Django 4.2.11 on 2024-04-09 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 11, 21, 14, 873979, tzinfo=datetime.timezone.utc)),
        ),
    ]
