# Generated by Django 4.2.11 on 2024-04-12 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_classsession_total_active_days_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 8, 10, 41, 308996, tzinfo=datetime.timezone.utc)),
        ),
    ]
