# Generated by Django 4.2.11 on 2024-04-12 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_student_year_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 8, 41, 29, 111564, tzinfo=datetime.timezone.utc)),
        ),
    ]
