# Generated by Django 4.2.11 on 2024-05-13 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 11, 4, 51, 231857, tzinfo=datetime.timezone.utc)),
        ),
    ]
