# Generated by Django 4.2.11 on 2024-05-25 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 8, 30, 30, 895947, tzinfo=datetime.timezone.utc)),
        ),
    ]
