# Generated by Django 4.2.11 on 2024-04-14 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_student_reg_no_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(default=None, related_name='teacher_subject', to='administration.subject'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 9, 31, 55, 140519, tzinfo=datetime.timezone.utc)),
        ),
    ]
