# Generated by Django 4.2.11 on 2024-05-26 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 11, 3, 4, 238267, tzinfo=datetime.timezone.utc)),
        ),
    ]
