# Generated by Django 4.2.11 on 2024-04-15 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_division_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='attendence_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_notification', to='administration.classsession'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 8, 3, 53, 181534, tzinfo=datetime.timezone.utc)),
        ),
    ]
