# Generated by Django 4.2.11 on 2024-04-15 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_classsession_attendence_active_notification_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='test_questions_table_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 11, 57, 17, 143465, tzinfo=datetime.timezone.utc)),
        ),
    ]
