# Generated by Django 4.2.11 on 2024-05-05 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0005_alter_otp_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_edited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.ManyToManyField(default=None, related_name='teachers_edited_department', to='administration.department')),
                ('subjects', models.ManyToManyField(default=None, related_name='teacher_edited_subject', to='administration.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_edited_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
